<a href="https://colab.research.google.com/github/xqunt/Site_Codigos_Analise/blob/master/Cleber_Fundamentus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://tradingcomdados.com/images/logotipo/logotipo-trading-com-dados.svg" width="300" align="left"/>

##Pandas e Fundamentus

Documentação da lib utilizada: 
- https://pandas.pydata.org/docs/
- https://pypi.org/project/fundamentus/

- Esse código não é uma recomendação de investimento e deve ser utilizado somente para fins educacionais.
- Autor: https://www.linkedin.com/in/arthur-camargo/

###Importando Bibliotecas

In [2]:
!pip install fundamentus
!pip install plotly

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting fundamentus
  Downloading fundamentus-0.2.0-py3-none-any.whl (13 kB)
Collecting requests-cache>=0.5.2
  Downloading requests_cache-1.0.1-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.7/58.7 KB 1.7 MB/s eta 0:00:00
Requirement already satisfied: requests>=2.25.1 in /usr/local/lib/python3.9/dist-packages (from fundamentus) (2.27.1)
Requirement already satisfied: tabulate>=0.8.7 in /usr/local/lib/python3.9/dist-packages (from fundamentus) (0.8.10)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.9/dist-packages (from fundamentus) (1.4.4)
Requirement already satisfied: lxml>=4.6.2 in /usr/local/lib/python3.9/dist-packages (from fundamentus) (4.9.2)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.9/dist-packages (from pandas>=1.1.5->fundamentus) (1.22.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=1.1.5->fundamentus) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=1.1.5->fundamentus) (2.8.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests>=2.25.1->fundamentus) (1.26.15)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests>=2.25.1->fundamentus) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests>=2.25.1->fundamentus) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests>=2.25.1->fundamentus) (3.4)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.9/dist-packages (from requests-cache>=0.5.2->fundamentus) (22.2.0)
Collecting url-normalize>=1.4
  Downloading url_normalize-1.4.3-py2.py3-none-any.whl (6.8 kB)
Collecting cattrs>=22.2
  Downloading cattrs-22.2.0-py3-none-any.whl (35 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests-cache>=0.5.2->fundamentus) (3.2.0)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.9/dist-packages (from cattrs>=22.2->requests-cache>=0.5.2->fundamentus) (1.1.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.8.1->pandas>=1.1.5->fundamentus) (1.16.0)
Installing collected packages: url-normalize, cattrs, requests-cache, fundamentus
Successfully installed cattrs-22.2.0 fundamentus-0.2.0 requests-cache-1.0.1 url-normalize-1.4.3
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: plotly in /usr/local/lib/python3.9/dist-packages (5.13.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.9/dist-packages (from plotly) (8.2.2)

In [3]:
import fundamentus
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from plotly.subplots import make_subplots

##Pandas

In [4]:
df = fundamentus.get_resultado()

In [5]:
df.head()

Multiples,cotacao,pl,pvp,psr,dy,pa,pcg,pebit,pacl,evebit,evebitda,mrgebit,mrgliq,roic,roe,liqc,liq2m,patrliq,divbpatr,c5y
papel,,,,,,,,,,,,,,,,,,,,
AALR3,22.54,-11.70,2.81,2.457,0.0000,1.019,-13.74,-210.51,-2.32,-274.95,33.14,-0.0117,-0.2021,-0.0055,-0.2399,0.71,10620900.0,9.496960e+08,1.09,0.0073
ABCB3,0.00,0.00,0.00,0.000,0.0000,0.000,0.00,0.00,0.00,0.00,0.00,0.0000,0.0000,0.0000,0.1537,0.00,0.0,5.205390e+09,0.00,0.2753
ABCB4,16.54,4.67,0.72,0.000,0.0655,0.000,0.00,0.00,0.00,0.00,0.00,0.0000,0.0000,0.0000,0.1537,0.00,15113400.0,5.205390e+09,0.00,0.2753
ABEV3,14.43,15.72,2.77,2.851,0.0528,1.647,-83.44,14.84,-13.52,14.08,10.37,0.1922,0.1868,0.1546,0.1764,0.93,434982000.0,8.195560e+10,0.05,0.1331
ABYA3,4.91,-214.80,1.76,2.055,0.0000,0.527,1.98,19.96,-2.75,33.67,33.67,0.1029,-0.0096,0.0278,-0.0082,2.09,0.0,2.920600e+08,1.31,0.1641

In [6]:
type(df)

pandas.core.frame.DataFrame

In [7]:
df.index

Index(['AALR3', 'ABCB3', 'ABCB4', 'ABEV3', 'ABYA3', 'ACES3', 'ACES4', 'ADHM3',
       'AEDU11', 'AEDU3',
       ...
       'WHRL4', 'WISA3', 'WISA4', 'WIZC3', 'WLMM3', 'WLMM4', 'WMBY3', 'WSON33',
       'YDUQ3', 'ZAMP3'],
      dtype='object', name='papel', length=969)

In [8]:
lista_de_ativos = df.index
lista_de_ativos

Index(['AALR3', 'ABCB3', 'ABCB4', 'ABEV3', 'ABYA3', 'ACES3', 'ACES4', 'ADHM3',
       'AEDU11', 'AEDU3',
       ...
       'WHRL4', 'WISA3', 'WISA4', 'WIZC3', 'WLMM3', 'WLMM4', 'WMBY3', 'WSON33',
       'YDUQ3', 'ZAMP3'],
      dtype='object', name='papel', length=969)

In [9]:
df.columns

Index(['cotacao', 'pl', 'pvp', 'psr', 'dy', 'pa', 'pcg', 'pebit', 'pacl',
       'evebit', 'evebitda', 'mrgebit', 'mrgliq', 'roic', 'roe', 'liqc',
       'liq2m', 'patrliq', 'divbpatr', 'c5y'],
      dtype='object', name='Multiples')

In [10]:
lista_de_indicadores = df.columns

In [11]:
lista_de_indicadores

Index(['cotacao', 'pl', 'pvp', 'psr', 'dy', 'pa', 'pcg', 'pebit', 'pacl',
       'evebit', 'evebitda', 'mrgebit', 'mrgliq', 'roic', 'roe', 'liqc',
       'liq2m', 'patrliq', 'divbpatr', 'c5y'],
      dtype='object', name='Multiples')

In [12]:
type(lista_de_indicadores)

pandas.core.indexes.base.Index

In [13]:
#df.info retorna informaçãoes sobre o tipo de dados e ausência de nulls
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 969 entries, AALR3 to ZAMP3
Data columns (total 20 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   cotacao   969 non-null    float64
 1   pl        969 non-null    float64
 2   pvp       969 non-null    float64
 3   psr       969 non-null    float64
 4   dy        969 non-null    float64
 5   pa        969 non-null    float64
 6   pcg       969 non-null    float64
 7   pebit     969 non-null    float64
 8   pacl      969 non-null    float64
 9   evebit    969 non-null    float64
 10  evebitda  969 non-null    float64
 11  mrgebit   969 non-null    float64
 12  mrgliq    969 non-null    float64
 13  roic      969 non-null    float64
 14  roe       969 non-null    float64
 15  liqc      969 non-null    float64
 16  liq2m     969 non-null    float64
 17  patrliq   969 non-null    float64
 18  divbpatr  969 non-null    float64
 19  c5y       969 non-null    float64
dtypes: float64(20)
memory usage: 159.0+ KB

In [14]:
#Seleção pela coluna

df['dy']

papel
AALR3     0.0000
ABCB3     0.0000
ABCB4     0.0655
ABEV3     0.0528
ABYA3     0.0000
           ...
WLMM4     0.0459
WMBY3     0.0000
WSON33    0.0000
YDUQ3     0.0182
ZAMP3     0.0000
Name: dy, Length: 969, dtype: float64

In [15]:
#Pandas Series outro tipo de estrutura de dados trabalhado no Pandas, um vetor de dados com labels em índice e coluna formato 1x1

type(df['dy'])

pandas.core.series.Series

In [16]:
df.sort_values(by='pl', ascending=True)

Multiples,cotacao,pl,pvp,psr,dy,pa,pcg,pebit,pacl,evebit,evebitda,mrgebit,mrgliq,roic,roe,liqc,liq2m,patrliq,divbpatr,c5y
papel,,,,,,,,,,,,,,,,,,,,
GNDI3,66.95,-3584.82,5.84,3.423,0.0239,2.378,79.65,87.05,-6.21,91.13,50.88,0.0393,-0.0009,0.0309,-0.0016,1.17,0.00,7.116080e+09,0.53,0.2523
PLDN4,486.00,-553.07,1.08,0.919,0.0000,0.611,1.07,-75.56,3.10,-33.12,-33.12,-0.0122,-0.0017,-0.0127,-0.0020,10.81,0.00,2.899390e+08,0.01,0.1026
MEGA3,9.38,-530.25,1.13,2.397,0.0000,0.346,-42.94,11.12,-0.67,24.49,13.76,0.2155,-0.0033,0.0346,-0.0021,0.96,11577000.00,5.151090e+09,1.65,9.2252
LCSA4,35.09,-337.52,-228.00,79.738,0.0000,125.308,-202.27,-505.80,-96.61,-506.56,-506.56,-0.1577,-0.2363,-0.2874,0.6755,0.29,0.00,-3.775680e+08,-0.35,63.5407
BAUH4,78.10,-287.21,4.46,2.124,0.0000,2.684,36.79,52.18,129.39,51.73,31.42,0.0407,-0.0074,0.0721,-0.0155,1.21,3036.73,9.140800e+07,0.11,0.0173
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
UBBR11,14.75,1201.81,3.91,0.000,0.0000,0.000,0.00,0.00,0.00,0.00,0.00,0.0000,0.0000,0.0000,0.0033,0.00,0.00,1.031720e+10,0.00,0.1058
GUAR4,151.00,1450.16,14.32,8.911,0.0000,4.952,19.35,280.18,307.97,286.37,88.71,0.0318,0.0061,0.0227,0.0099,1.62,0.00,5.263090e+09,0.78,0.0249
UBBR3,18.00,1466.61,4.77,0.000,0.0000,0.000,0.00,0.00,0.00,0.00,0.00,0.0000,0.0000,0.0000,0.0033,0.00,0.00,1.031720e+10,0.00,0.1058
MLFT4,22.39,6224.98,11.51,46.353,0.0000,5.854,100.42,103.43,-26.71,106.22,78.73,0.4482,0.0126,0.0735,0.0018,1.27,0.00,4.093330e+09,0.76,0.0843
BBTG12,3.15,132993.00,37998.00,0.000,0.0000,0.000,0.00,0.00,0.00,0.00,0.00,0.0000,0.0000,0.0000,0.2857,0.00,0.00,7.000000e+03,0.00,0.0000

In [17]:
#loc localiza linhas e colunas pelo seu label
df.loc['GNDI3']

Multiples
cotacao     6.695000e+01
pl         -3.584820e+03
pvp         5.840000e+00
psr         3.423000e+00
dy          2.390000e-02
pa          2.378000e+00
pcg         7.965000e+01
pebit       8.705000e+01
pacl       -6.210000e+00
evebit      9.113000e+01
evebitda    5.088000e+01
mrgebit     3.930000e-02
mrgliq     -9.000000e-04
roic        3.090000e-02
roe        -1.600000e-03
liqc        1.170000e+00
liq2m       0.000000e+00
patrliq     7.116080e+09
divbpatr    5.300000e-01
c5y         2.523000e-01
Name: GNDI3, dtype: float64

In [18]:
df.loc[['GNDI3'],['pl']]

Multiples       pl
papel
GNDI3     -3584.82

In [19]:
#iloc localiza linha e coluna pela sua posição, lembre-se python inicia a indexação em 0 (primeira posição)
df.iloc[[0],[0]]

Multiples  cotacao
papel
AALR3        22.54

In [20]:
df.loc[['GNDI3', 'MELK3'],['dy']]

Multiples      dy
papel
GNDI3      0.0239
MELK3      0.0730

In [29]:
df.loc[['SUZB5','CSNA3' , 'MRFG3' , 'KLBN3' , 'JBSS3', 'CMIN3'] , ['pl', 'pvp', 'roe', 'evebitda', 'divbpatr'  ]]

Multiples     pl   pvp     roe  evebitda  divbpatr       patrliq
papel
SUZB5       1.20  0.85  0.7072      3.03      2.26  3.306100e+10
CSNA3      12.69  1.01  0.0797      3.65      2.10  1.948950e+10
MRFG3       1.01  0.75  0.7479      3.81     11.63  5.569860e+09
KLBN3       4.43  2.17  0.4908      4.30      2.88  9.559480e+09
JBSS3       2.50  0.84  0.3335     -4.48      1.99  4.634420e+10
CMIN3       8.57  2.22  0.2589      4.46      0.74  1.139340e+10

In [30]:
#filtros usados em conjunto através do operador & 

df[(df.pl > 15) & (df.dy > 0.05)]

Multiples,cotacao,pl,pvp,psr,dy,pa,pcg,pebit,pacl,evebit,evebitda,mrgebit,mrgliq,roic,roe,liqc,liq2m,patrliq,divbpatr,c5y
papel,,,,,,,,,,,,,,,,,,,,
ABEV3,14.43,15.72,2.77,2.851,0.0528,1.647,-83.44,14.84,-13.52,14.08,10.37,0.1922,0.1868,0.1546,0.1764,0.93,4.349820e+08,8.195560e+10,0.05,0.1331
AGRO3,24.04,19.77,1.20,1.936,0.2186,0.731,3.87,14.10,-58.61,17.32,11.76,0.1373,0.0979,0.0604,0.0607,1.99,1.222210e+07,2.051180e+09,0.43,0.3367
CEPE5,40.12,19.07,1.94,0.377,0.0934,0.227,2.87,2.61,-0.38,8.33,6.31,0.1446,0.0198,0.1000,0.1018,1.40,0.000000e+00,1.543000e+09,4.86,1.2105
CEPE6,43.00,20.44,2.08,0.405,0.0959,0.243,3.08,2.80,-0.40,8.52,6.45,0.1446,0.0198,0.1000,0.1018,1.40,0.000000e+00,1.543000e+09,4.86,1.2105
CPLE11,34.77,17.11,0.91,0.868,0.1250,0.383,8.77,4.75,-0.99,7.19,5.42,0.1828,0.0524,0.0892,0.0534,1.30,1.074030e+07,2.081740e+10,0.60,0.1227
CPLE3,6.34,15.60,0.83,0.791,0.1270,0.349,7.99,4.33,-0.90,6.77,5.11,0.1828,0.0524,0.0892,0.0534,1.30,1.063300e+07,2.081740e+10,0.60,0.1227
CPLE6,7.15,17.60,0.94,0.892,0.1239,0.394,9.01,4.88,-1.02,7.32,5.53,0.1828,0.0524,0.0892,0.0534,1.30,9.828390e+07,2.081740e+10,0.60,0.1227
CRPG3,55.00,23.35,1.97,1.988,0.0865,1.510,3.25,64.99,4.23,56.66,29.75,0.0306,0.0851,0.0312,0.0845,4.67,0.000000e+00,8.088910e+08,0.01,0.0999
CSED3,2.09,116.13,0.55,0.378,0.0652,0.163,1.65,2.69,-0.35,3.45,1.87,0.1405,0.0033,0.0753,0.0047,1.71,2.097100e+06,1.405390e+09,0.76,0.1016
DESK3,8.37,20.10,1.03,1.357,4.0141,0.383,-15.88,4.50,-0.82,7.43,4.97,0.3017,0.0774,0.0981,0.0514,0.87,1.759050e+06,9.335760e+08,0.94,1.0625
EQPA6,10.69,15.17,8.17,2.774,0.0826,1.846,20.30,9.59,-4.31,11.17,9.68,0.2894,0.1828,0.2437,0.5385,1.36,0.000000e+00,2.890070e+09,1.93,0.1331
LPSB3,1.49,18.38,1.15,1.128,0.0507,0.561,6.88,8.22,-2.09,6.15,3.87,0.1371,0.1385,0.0806,0.0628,1.47,3.268370e+05,1.904670e+08,0.00,0.1701
MODL3,1.51,37.33,0.85,0.000,0.0647,0.000,0.00,0.00,0.00,0.00,0.00,0.0000,0.0000,0.0000,0.0227,0.00,6.038540e+06,1.252920e+09,0.00,0.4437
PATI3,50.60,21.74,1.44,0.519,0.0575,0.637,1.19,22.53,2.35,22.93,18.96,0.0231,0.0239,0.0522,0.0663,2.83,1.272500e+03,8.403730e+08,0.74,0.2836
PATI4,39.00,16.76,1.11,0.400,0.0746,0.491,0.92,17.37,1.81,17.76,14.69,0.0231,0.0239,0.0522,0.0663,2.83,6.292300e+02,8.403730e+08,0.74,0.2836
RAIZ4,2.83,304.00,1.38,0.120,0.0838,0.279,3.73,8.86,-0.87,20.73,5.51,0.0135,0.0006,0.0406,0.0045,1.19,8.521820e+07,2.119640e+10,2.08,0.1546
STBP3,8.59,17.29,3.55,3.843,0.0721,1.707,30.01,13.12,-5.31,12.63,9.24,0.2929,0.2223,0.1567,0.2052,1.41,4.120840e+07,2.092880e+09,0.16,0.2136
VIVT3,39.00,15.88,0.95,1.350,0.0785,0.545,-13.28,10.75,-1.94,13.58,4.38,0.1256,0.0845,0.0551,0.0597,0.78,8.885240e+07,6.840370e+10,0.28,0.0197

In [ ]:
df.loc[:,['pl']] > 10

##Exercício

Criar um gráfico que sumarize um grupo de métricas fundamentalistas de um determinado setor

In [ ]:
#lista de empresas através do código do setor

fundamentus.list_papel_setor(8)

In [ ]:
setor = fundamentus.list_papel_setor(8)
setor

In [ ]:
df.query('index in @setor')

In [ ]:
df.query('index in @setor').loc[:,['mrgebit', 'mrgliq', 'roic', 'roe']]

In [ ]:
varejo = df.query('index in @setor').loc[:,['mrgebit', 'mrgliq', 'roic', 'roe']]
varejo

In [ ]:
fig = make_subplots(rows=2,
                    cols=2,
                    row_heights=[4,4],
                    column_widths=[4,4],
                    subplot_titles=('Margem EBTIDA', 'Margem Líquida', 'ROIC', 'ROE'),
                    shared_xaxes=False)
fig.add_trace(go.Bar(name='Margem_Ebtida', x=varejo.index, y=varejo['mrgebit']), row=1, col=1)
fig.add_trace(go.Bar(name='Margem_Liquida', x=varejo.index, y=varejo['mrgliq']), row=1, col=2)
fig.add_trace(go.Bar(name='ROIC', x=varejo.index, y=varejo['roic']), row=2, col=1)
fig.add_trace(go.Bar(name='ROE', x=varejo.index, y=varejo['roe']), row=2, col=2)
fig.update_layout(title_text='<b>Overview Rentabilidade Varejo<b>', 
                  template='plotly_dark',#template pré-definido da plotly
                  showlegend=False, #esconder ou mostrar legenda
                  height=500, #altura
                  width=900) #largura
fig.show()

In [ ]:
varejo2 = df.query('index in @setor').loc[:,['pl', 'pvp', 'evebitda', 'dy']]
varejo2

In [ ]:
#ORDENANDO OS VALORES

#Para fazer isso deixar o shared xaxes = False  e adicionar o fig.update_xaxes(categoryorder='total descending')

fig = make_subplots(rows=2,
                    cols=2,
                    row_heights=[5,5],
                    column_widths=[3,3],
                    subplot_titles=('Preço/Lucro', 'P/VP', 'EV/EBTIDA', 'Dividend Yeld'),
                    shared_xaxes=False)
fig.add_trace(go.Bar(name='Margem_Ebtida', x=varejo2.index, y=varejo2['pl']), row=1, col=1)
fig.add_trace(go.Bar(name='Margem_Liquida', x=varejo2.index, y=varejo2['pvp']), row=1, col=2)
fig.add_trace(go.Bar(name='ROIC', x=varejo2.index, y=varejo2['evebitda']), row=2, col=1)
fig.add_trace(go.Bar(name='ROE', x=varejo2.index, y=varejo2['dy']), row=2, col=2)
fig.update_layout(title_text='<b>Avaliação por Múltiplos Varejo<b>', 
                  template='plotly_dark',#template pré-definido da plotly
                  showlegend=False, #esconder ou mostrar legenda
                  height=500, #altura
                  width=900) #largura
fig.update_xaxes(categoryorder='total descending')
fig.show()